import React from 'react';

// const testArticles = [
//     { id: 1, title: "first post", content: "Ante integer dignissim egestas enim tortor aptent imperdiet. Rhoncus himenaeos sapien sit magnis nibh ac orci metus netus tristique feugiat lorem. Magnis elementum risus, accumsan ut ante congue mauris scelerisque. Facilisis quam accumsan mauris ornare aliquam rhoncus. Parturient metus hac quis, quis auctor sollicitudin hendrerit. Class cubilia nibh penatibus, massa nec venenatis. Neque aliquet nam cum massa. Inceptos dictum montes, montes felis. Urna." },
//     { id: 2, title: "second post", content: "Euismod mus urna commodo blandit, pulvinar mi viverra class ad imperdiet. Viverra montes fusce viverra lacinia sagittis vel natoque consequat leo ipsum dictumst. Quisque adipiscing turpis sollicitudin aptent nascetur a? Quisque mattis fermentum leo semper erat parturient nulla duis risus volutpat. Nascetur cursus, lorem duis convallis suspendisse rhoncus blandit condimentum blandit. Justo vulputate, suspendisse sem quisque maecenas. Justo himenaeos gravida elementum cum condimentum est ipsum habitant. Sagittis facilisi, himenaeos dolor enim ac vehicula. Risus rhoncus." },
//     { id: 3, title: "third post", content: "Proin tincidunt fames nulla tristique iaculis purus condimentum mus accumsan. Iaculis etiam a ad. Non sollicitudin condimentum sit dolor arcu. Sociosqu faucibus metus condimentum nulla sapien tempor sapien turpis. Nibh ad dignissim magnis elementum nec a habitant dictum nascetur facilisi! Rutrum, tortor faucibus potenti consequat. Est commodo scelerisque enim imperdiet lacus ad quisque, ad sodales. Nec tristique, mattis ridiculus potenti enim ridiculus bibendum phasellus. Sem; donec nunc convallis amet. Nascetur velit velit pretium tristique ipsum sit tincidunt nisi. Euismod himenaeos etiam euismod est sit fringilla integer neque litora gravida fusce. Enim aenean volutpat nibh posuere purus taciti class nisi." },
//     { id: 4, title: "fourth post", content: "Inceptos venenatis nascetur parturient. Sit vulputate pellentesque elementum cras integer dolor taciti tellus ipsum dolor. Vehicula parturient morbi, diam vivamus. Consequat, natoque lobortis litora nulla. Id pellentesque tortor, sociosqu fringilla taciti habitasse libero habitant. Iaculis fames, platea montes consectetur. Consectetur montes litora augue ridiculus per sodales sapien convallis sociosqu? Vulputate mattis pharetra erat hendrerit tortor ornare elit nibh integer. Congue id, nullam quisque habitasse at auctor! Vestibulum lectus nibh odio diam conubia ridiculus mollis morbi. Platea massa ridiculus nibh magna. Nec gravida tortor class neque eleifend neque." },
//     { id: 5, title: "fifth post", content: "Eleifend gravida leo iaculis, cras sociosqu fringilla natoque cubilia. Interdum euismod convallis ante blandit himenaeos odio vehicula vivamus, ut auctor tortor. Hac parturient fames dictum. Netus vitae id auctor sit magna pulvinar sodales etiam sagittis taciti tellus. Lorem amet fringilla sagittis eros porttitor et molestie. Eget lorem hendrerit amet rutrum tempus lectus ullamcorper lorem arcu. Lectus justo himenaeos nibh ad faucibus. Praesent placerat consequat accumsan elementum, tristique vel elit tincidunt rutrum velit? Convallis condimentum magnis tristique dictumst est facilisis lacus conubia rhoncus magna quis. Adipiscing sem molestie congue. Libero cursus egestas cum, porta hac cubilia!" },
//     { id: 6, title: "sixth post", content: "testtesttest" }
// ]

function MenuItem(props) {
    return(
        <li>{}</li>
    )
}

export default MenuItem;